# Generated by Django 3.1 on 2020-08-09 06:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0002_cheese_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='country_of_origin',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country of Origin'),
        ),
    ]
